services:
  albert-conversation:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_HASH=${BUILD_HASH:-dev-build}
    container_name: albert-conversation
    volumes:
      - albert-conversation:/app/backend/data
      - ./src:/app/src
      - ./backend:/app/backend
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}'
      - 'OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
      - 'OPENAI_API_BASE_URLS=${OPENAI_API_BASE_URLS}'
      - 'OPENAI_API_KEYS=${OPENAI_API_KEYS}'
      - 'NODE_OPTIONS=--max-old-space-size=8192'
      - 'FRONTEND_URL=${FRONTEND_URL}'
      - 'BACKEND_URL=${BACKEND_URL}'
      # ProConnect
      - 'PROCONNECT_CLIENT_ID=${PROCONNECT_CLIENT_ID}'
      - 'PROCONNECT_CLIENT_SECRET=${PROCONNECT_CLIENT_SECRET}'
      - 'PROCONNECT_SESSION_DURATION=${PROCONNECT_SESSION_DURATION}'
      - 'SERVER_METADATA_URL=${SERVER_METADATA_URL}'
      # Redis
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    depends_on:
      - redis
    networks:
      - albert-network
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: albert-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - albert-network
    restart: unless-stopped

volumes:
  albert-conversation: {}
  redis-data: {}

networks:
  albert-network:
    driver: bridge
